//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 03:35:00 PM EEST 
//


package com.marst89.modelForXstream;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

import java.math.BigDecimal;
import java.math.BigInteger;

@XStreamAlias("shiporder")
public class Shiporder {

    protected String orderperson;
    protected Shiporder.Shipto shipto;
    protected Shiporder.Item item;
    @XStreamAsAttribute
    protected String orderid;

    /**
     * Gets the value of the orderperson property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrderperson() {
        return orderperson;
    }

    /**
     * Sets the value of the orderperson property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrderperson(String value) {
        this.orderperson = value;
    }

    public Shiporder.Shipto getShipto() {
        return shipto;
    }


    public void setShipto(Shiporder.Shipto value) {
        this.shipto = value;
    }

    public Shiporder.Item getItem() {
        return item;
    }


    public void setItem(Shiporder.Item value) {
        this.item = value;
    }

    public String getOrderid() {
        return orderid;
    }

    public void setOrderid(String value) {
        this.orderid = value;
    }

    public static class Item {
        protected String title;
        protected String note;
        protected BigInteger quantity;
        protected BigDecimal price;

        public String getTitle() {
            return title;
        }
        public void setTitle(String value) {
            this.title = value;
        }
        public String getNote() {
            return note;
        }

        public void setNote(String value) {
            this.note = value;
        }


        public BigInteger getQuantity() {
            return quantity;
        }


        public BigDecimal getPrice() {
            return price;
        }

        public void setPrice(BigDecimal value) {
            this.price = value;
        }

    }




    public static class Shipto {
        protected String name;
        protected String address;
        protected String city;
        protected String country;

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        public String getAddress() {
            return address;
        }

        public void setAddress(String value) {
            this.address = value;
        }

        public String getCity() {
            return city;
        }

        public void setCity(String value) {
            this.city = value;
        }

        public String getCountry() {
            return country;
        }

        public void setCountry(String value) {
            this.country = value;
        }
    }

}
